{{- $KafkaOperator := lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "kafkas.kafka.strimzi.io" -}}
{{- if $KafkaOperator }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: {{ $.Values.global.mirrormaker2.name }}
  namespace: {{ $.Values.global.mirrormaker2.mirrormaker2_namespace }}
spec:
  version: {{ $.Values.global.mirrormaker2.version }}
  replicas: 1
  connectCluster: "target-cluster" # Must be the target cluster
  clusters:
  - alias: "source-cluster" # Source cluster
    bootstrapServers: {{ $.Values.global.kafka.internalbootstrapServers }} # might have to wrap with ""
    # bootstrapServers: my-kafka-cluster-kafka-bootstrap:9093
    tls:
      trustedCertificates:
        - secretName: {{ .Values.global.kafka.kafka_cluster_name }}-cluster-ca-cert
          certificate: ca.crt
    authentication:
      type: tls
      certificateAndKey:
        secretName: {{ .Values.global.kafka.Mirrormaker2_User }}
        certificate: user.crt
        key: user.key
  - alias: "target-cluster" # Target cluster
    bootstrapServers: {{ $.Values.global.kafka.secondary_internalbootstrapServers }} # might have to wrap with ""
    # bootstrapServers: my-other-kafka-cluster-kafka-bootstrap:9093
    tls:
      trustedCertificates:
        - secretName: {{ .Values.global.kafka.secondary_kafka_cluster_name }}-cluster-ca-cert
          certificate: ca.crt
    authentication:
      type: tls
      certificateAndKey:
        secretName: {{ .Values.global.kafka.secondary_Mirrormaker2_User }}
        certificate: user.crt
        key: user.key
    config:
      # -1 means it will use the default replication factor configured in the broker
      config.storage.replication.factor: -1
      offset.storage.replication.factor: -1
      status.storage.replication.factor: -1
  mirrors:
    - sourceCluster: "source-cluster"
      targetCluster: "target-cluster"
      sourceConnector:
        # The sourceConnector and checkpointConnector configurations specify tasksMax: 1, 
        # which limits the number of tasks to one. 
        # Depending on your replication load, 
        # you might want to increase this value to improve performance.
        tasksMax: 1
        config:
          # -1 means it will use the default replication factor configured in the broker
          replication.factor: -1
          offset-syncs.topic.replication.factor: -1
          sync.topic.acls.enabled: "false"
          refresh.topics.interval.seconds: 600
          create.missing.topics.enabled: "true"
          config.storage.topic: connect-fixed-namespace-configs
          offset.storage.topic: connect-fixed-namespace-offsets
          status.storage.topic: connect-fixed-namespace-status
      checkpointConnector:
        tasksMax: 1
        config:
          # -1 means it will use the default replication factor configured in the broker
          checkpoints.topic.replication.factor: -1
          sync.group.offsets.enabled: "false"
          refresh.groups.interval.seconds: 600
      topicsPattern: ".*"
      groupsPattern: ".*"
{{- end }}